# Project information
site_name: HyPhy - Hypothesis Testing using Phylogenies
site_description: Information, documentation, and news about the HyPhy software package
site_author: VEG
site_url: http://veg.github.io/hyphy-site/

# Copyright
copyright: null

# Documentation and theme
theme_dir: material

# extra_templates

# Options
extra:
  version: 0.2.5
  logo: images/logo.svg
  github:
    download_release: true
  author:
    github: veg
    twitter: hyphy_software

# Extensions
markdown_extensions:
  - admonition
  - toc:
      permalink: '#'
  - mdx_math:
      enable_dollar_delimiter: True

extra_javascript:
    - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML
    - assets/mathjaxhelper.js

# Google Analytics
google_analytics: ['hyphy.org', 'veg.github.io']

# Page tree
pages:
  - Home: 'index.html'
  - About : 'about.md'
  - Download : 'register.html'
  - _Real_Download : 'download.md'
  - Installation: 'installation.md'
  - Getting Started : 'getting-started.md'
  - Methods: 'methods/index.md'
  - Tutorials: 'tutorials/index.md'
  - Batch Language : 'hbl-reference/index.md'
  - _Library : 'hbl-reference/libv3.md'
#  - Glossary: 'glossary.md'
  - Resources: 'resources.md'
  - '_________' : 'methods/general.md'
  - '_________' : 'methods/selection-methods.md'
  - '_________' : 'methods/stand-alone-analyses.md'
  - '_________' : 'methods/other/evo.md'
  - '________' : 'methods/other/contrast-fel.md'
  # '________' will hide the item from the toc
#  - Scripting language: 'language.md'
  - '_________' : 'tutorials/CLI-tutorial.md'
  - '_________' : 'tutorials/CL-prompt-tutorial.md'
  - '_________' : 'tutorials/gui-tutorial.md'
  - '_________' : 'tutorials/phylotree.md' 
#    - v2.3 Quick Start : 'tutorials/dev-branch-tutorial.md'
